### ISSUE TITLE
initial onboarding 

### ISSUE THREAD

**Issue by birojnayak** [dotnet/dotnet-monitor#2626]
Hi Guys,
I was trying to build the repo first time https://github.com/dotnet/dotnet-monitor/blob/main/documentation/building.md . Did git clone, build (success), test(failed). Any other pre-req or software needs to be installed to run the full suite ? Attached a txt file to see the failures.

`
 at Microsoft.Diagnostics.Tools.Monitor.TaskCompletionSourceExtensions.WithCancellation[T](TaskCompletionSource`1 source, CancellationToken token) in C:\Users\biroj\source\repos\dotnet-monitor\src\Tools\dotnet-monitor\TaskCompletionSourceExtensions.cs:line 30
   at Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions.CollectionRuleActionBase`1.StartAsync(CollectionRuleMetadata collectionRuleMetadata, CancellationToken token) in C:\Users\biroj\source\repos\dotnet-monitor\src\Tools\dotnet-monitor\CollectionRules\Actions\CollectionRuleActionBase.cs:line 57
   at Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions.ActionListExecutor.ExecuteActions(CollectionRuleContext context, Action startCallback, CancellationToken cancellationToken) in C:\Users\biroj\source\repos\dotnet-monitor\src\Tools\dotnet-monitor\CollectionRules\ActionListExecutor.cs:line 102
   at Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions.ActionListExecutor.ExecuteActions(CollectionRuleContext context, Action startCallback, CancellationToken cancellationToken) in C:\Users\biroj\source\repos\dotnet-monitor\src\Tools\dotnet-monitor\CollectionRules\ActionListExecutor.cs:line 122
   at Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions.ActionListExecutor.ExecuteActions(CollectionRuleContext context, Action startCallback, CancellationToken cancellationToken) in C:\Users\biroj\source\repos\dotnet-monitor\src\Tools\dotnet-monitor\CollectionRules\ActionListExecutor.cs:line 153
   at Microsoft.Diagnostics.Monitoring.Tool.UnitTests.ActionDependencyAnalyzerTests.&lt;&gt;c__DisplayClass6_0.&lt;&lt;DependenciesTest&gt;b__1&gt;d.MoveNext() in C:\Users\biroj\source\repos\dotnet-monitor\src\Tests\Microsoft.Diagnostics.Monitoring.Tool.UnitTests\ActionDependencyAnalyzerTests.cs:line 94
--- End of stack trace from previous location ---
   at Microsoft.Diagnostics.Monitoring.Tool.UnitTests.TestHostHelper.CreateCollectionRulesHost(ITestOutputHelper outputHelper, Action`1 setup, Func`2 hostCallback, Action`1 servicesCallback, Action`1 loggingCallback, List`1 overrideSource) in C:\Users\biroj\source\repos\dotnet-monitor\src\Tests\Microsoft.Diagnostics.Monitoring.Tool.UnitTests\TestHostHelper.cs:line 32
   at Microsoft.Diagnostics.Monitoring.Tool.UnitTests.TestHostHelper.CreateCollectionRulesHost(ITestOutputHelper outputHelper, Action`1 setup, Func`2 hostCallback, Action`1 servicesCallback, Action`1 loggingCallback, List`1 overrideSource) in C:\Users\biroj\source\repos\dotnet-monitor\src\Tests\Microsoft.Diagnostics.Monitoring.Tool.UnitTests\TestHostHelper.cs:line 37
   at Microsoft.Diagnostics.Monitoring.Tool.UnitTests.ActionDependencyAnalyzerTests.DependenciesTest() in C:\Users\biroj\source\repos\dotnet-monitor\src\Tests\Microsoft.Diagnostics.Monitoring.Tool.UnitTests\ActionDependencyAnalyzerTests.cs:line 71
--- End of stack trace from previous location ---</pre></span><br></div>
`

C:\Users\biroj>dotnet --list-sdks
3.1.423 [C:\Program Files\dotnet\sdk]
6.0.304 [C:\Program Files\dotnet\sdk]
6.0.401 [C:\Program Files\dotnet\sdk]
7.0.100-rc.1.22431.12 [C:\Program Files\dotnet\sdk]

C:\Users\biroj>dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.0-rc.1.22427.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.0-rc.1.22426.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.0-rc.1.22427.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
[Microsoft.Diagnostics.Monitoring.Tool.UnitTests_net6.txt](https://github.com/dotnet/dotnet-monitor/files/9719561/Microsoft.Diagnostics.Monitoring.Tool.UnitTests_net6.txt)

**Comment by jander-msft** [comment]
No other prerequisites are required. The last time this test failed was about two weeks ago (https://runfo.azurewebsites.net/view/build/?number=27097), but it probably has run several hundreds of times since then without issue.

**Comment by jander-msft** [comment]
Please try rerunning and it should succeed. If it more consistently fails, please feel free to log a bug specifically about the failing test and as much detail of the test results and the ability to repro it as much as you can.
