### ISSUE TITLE
Changing default port/endpoint.

### ISSUE THREAD

**Issue by ernesto1596** [dotnet/dotnet-monitor#2912]
I am attempting to change the default port/endpoint for dotnet monitor in k8s. I tried following the suggested config change in from this issue: https://github.com/dotnet/dotnet-monitor/issues/1265

YAML configuration
```yaml

        - name: dotnetmonitor
          image: "mcr.microsoft.com/dotnet/nightly/monitor:6.1"
          args: ["--no-auth"]
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 52307
          env:
            - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
              value: Listen
            - name: DOTNETMONITOR_DiagnosticPort__EndpointName
              value: /diag/port
            - name: DOTNETMONITOR_Storage__DumpTempFolder
              value: /dumps
            - name: DOTNETMONITOR_Urls
              value: http://localhost:52307
             # I was not sure which metrics env var should be used so I included both.
            - name: DOTNETMONITOR_Metrics_Endpoints
              value: http://+:52307
            - name: DOTNETMONITOR_MetricsUrls
              value: http://+:52307
          volumeMounts:
            - name: diagnostics
              mountPath: /diag
            - name: dumps
              mountPath: /dumps
```

Logs:
```
{
    "Timestamp": "2022-11-17T20:09:03.8744520Z",
    "EventId": 60,
    "LogLevel": "Information",
    "Category": "Microsoft.Diagnostics.Tools.Monitor.Startup",
    "Message": "Tell us about your experience with dotnet monitor: https://aka.ms/dotnet-monitor-survey",
    "State": {
      "Message": "Tell us about your experience with dotnet monitor: https://aka.ms/dotnet-monitor-survey",
      "link": "https://aka.ms/dotnet-monitor-survey",
      "{OriginalFormat}": "Tell us about your experience with dotnet monitor: {link}"
    },
    "Scopes": []
  },
  {
    "Timestamp": "2022-11-17T20:09:03.9640420Z",
    "EventId": 13,
    "LogLevel": "Warning",
    "Category": "Microsoft.Diagnostics.Tools.Monitor.Startup",
    "Message": "WARNING: Authentication has been disabled. This can pose a security risk and is not intended for production environments.",
    "State": {
      "Message": "WARNING: Authentication has been disabled. This can pose a security risk and is not intended for production environments.",
      "{OriginalFormat}": "WARNING: Authentication has been disabled. This can pose a security risk and is not intended for production environments."
    },
    "Scopes": []
  },
  {
    "Timestamp": "2022-11-17T20:09:04.3681718Z",
    "EventId": 0,
    "LogLevel": "Warning",
    "Category": "Microsoft.AspNetCore.Server.Kestrel",
    "Message": "Overriding address(es) \u0027http://localhost:52307\u0027. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.",
    "State": {
      "Message": "Overriding address(es) \u0027http://localhost:52307\u0027. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.",
      "addresses": "http://localhost:52307",
      "{OriginalFormat}": "Overriding address(es) \u0027{addresses}\u0027. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead."
    },
    "Scopes": []
  },
  {
    "Timestamp": "2022-11-17T20:09:04.5728071Z",
    "EventId": 9,
    "LogLevel": "Error",
    "Category": "Microsoft.Extensions.Hosting.Internal.Host",
    "Message": "BackgroundService failed",
    "Exception": "System.Threading.Tasks.TaskCanceledException: A task was canceled.    at Microsoft.Diagnostics.Monitoring.WebApi.MetricsService.ExecuteAsync(CancellationToken stoppingToken) in /_/src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsService.cs:line 71    at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)",
    "State": {
      "Message": "BackgroundService failed",
      "{OriginalFormat}": "BackgroundService failed"
    },
    "Scopes": []
  },
  {
    "Timestamp": "2022-11-17T20:09:04.6613198Z",
    "EventId": 10,
    "LogLevel": "Critical",
    "Category": "Microsoft.Extensions.Hosting.Internal.Host",
    "Message": "The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.",
    "Exception": "System.Threading.Tasks.TaskCanceledException: A task was canceled.    at Microsoft.Diagnostics.Monitoring.WebApi.MetricsService.ExecuteAsync(CancellationToken stoppingToken) in /_/src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsService.cs:line 71    at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)",
    "State": {
      "Message": "The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.",
      "{OriginalFormat}": "The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted."
    },
    "Scopes": []
  },
  {
    "Timestamp": "2022-11-17T20:09:04.6616810Z",
    "EventId": 0,
    "LogLevel": "Information",
    "Category": "Microsoft.Hosting.Lifetime",
    "Message": "Application is shutting down...",
    "State": {
      "Message": "Application is shutting down...",
      "{OriginalFormat}": "Application is shutting down..."
    },
    "Scopes": []
  }
```

Exception
```
Unhandled exception: System.IO.IOException: Failed to bind to address http://[::]:52325: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address in use
 ---> System.Net.Sockets.SocketException (98): Address in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Diagnostics.Tools.Monitor.Commands.CollectCommandHandler.Invoke(CancellationToken token, String[] urls, String[] metricUrls, Boolean metrics, String diagnosticPort, Boolean noAuth, Boolean tempApiKey, Boolean noHttpEgress) in /_/src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs:line 35
   at Microsoft.Diagnostics.Tools.Monitor.Commands.CollectCommandHandler.Invoke(CancellationToken token, String[] urls, String[] metricUrls, Boolean metrics, String diagnosticPort, Boolean noAuth, Boolean tempApiKey, Boolean noHttpEgress) in /_/src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs:line 66
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass9_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by kkeirstead** [comment]
Hey, let me see if I can work through this with you. I noticed a few small things in your config that need to be adjusted, feel free to give them a try and let us know if that fixes your issue.

- Change `DOTNETMONITOR_Metrics_Endpoints` to `DOTNETMONITOR_Metrics__Endpoints` (note the double underscore between "Metrics" and "Endpoints"). I'm assuming this is why you're seeing that `dotnet-monitor` is still referencing 52325 in the exception.
- Remove `DOTNETMONITOR_MetricsUrls` - I'll link you to the [documentation](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration.md#metrics-urls) that explains when to use that format and when to use the `Metrics__Endpoint` format.
- Change either `DotnetMonitor_Urls` or `DotnetMonitor_Metrics__Endpoints` so that they aren't both the same (e.g. 52307 and 52308) - otherwise, I believe you'll get an error saying that 52307 is already in use

I believe you should also be able to remove the `containerPort` section if you want, but hopefully that gets you up and running. And, as a side note, you currently have your version pinned to 6.1 - we've recently released `dotnet-monitor 7`, as well as several newer versions of `dotnet-monitor 6`, so I'd recommend changing the tag to get the latest features and fixes 😄
