### ISSUE TITLE
Manually specifying startup hook can be error prone

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-monitor#4238]
Take the following minimal deployment that enables the experimental exceptions feature (ignore the fact that exception collection doesn't work on the samples image due to trimming of startup hooks):

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-exampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exampleapp
  template:
    metadata:
      labels:
        app: exampleapp
    spec:
      restartPolicy: Always
      containers:
      - name: app
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: DOTNET_DiagnosticPorts
          value: /diag/dotnet-monitor.sock
        - name: DOTNET_STARTUP_HOOKS
          value: /diag/libs/8.0.0-preview.3.23180.9/any/net6.0/Microsoft.Diagnostics.Monitoring.StartupHook.dll
        volumeMounts:
        - mountPath: /diag
          name: diagvol
      - name: monitor
        image: mcr.microsoft.com/dotnet/nightly/monitor:8.0.0-preview.3
        args: [ "collect", "--urls", "http://localhost:52323", "--metricUrls", "http://+:52325", "--no-auth" ]
        imagePullPolicy: Always
        env:
        - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
          value: Listen
        - name: DOTNETMONITOR_Storage__DefaultSharedPath
          value: /diag
        - name: DOTNETMONITOR_InProcessFeatures__Enabled
          value: 'true'
        - name: DotnetMonitor_Experimental_Feature_Exceptions
          value: 'true'
        volumeMounts:
        - mountPath: /diag
          name: diagvol
      volumes:
      - name: diagvol
        emptyDir: {}
```

Note that the path of the startup hook is the following and contains the exact version of .NET Monitor:
```
/diag/libs/8.0.0-preview.3.23180.9/any/net6.0/Microsoft.Diagnostics.Monitoring.StartupHook.dll
```

Needing to specify a path that contains the .NET Monitor version is problematic; for any update to .NET Monitor, this version number will change. The vast majority of users will be using a floating tag (e.g. `mcr.microsoft.com/dotnet/nightly/monitor:8-preview`) whose version changes for every release. The target application will crash if any of the startup hook paths do not exist:
```
Unhandled exception. System.ArgumentException: Startup hook assembly '/diag/libs/8.0.0/any/net6.0/Microsoft.Diagnostics.Monitoring.StartupHook.dll' failed to load. See inner exception for details.
 ---> System.IO.FileNotFoundException: Could not load file or assembly '/diag/libs/8.0.0/any/net6.0/Microsoft.Diagnostics.Monitoring.StartupHook.dll'. The system cannot find the file specified.

File name: '/diag/libs/8.0.0/any/net6.0/Microsoft.Diagnostics.Monitoring.StartupHook.dll'
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr ptrNativeAssemblyBinder, UInt16* ilPath, UInt16* niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath startupHook)
   --- End of inner exception stack trace ---
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath startupHook)
   at System.StartupHookProvider.ProcessStartupHooks()
```

We need determine a way of creating a stable path (independent of the .NET Monitor version) so that it is predictable, more easily understood by a user, and doesn't change for minor and patch releases.

**Comment by jander-msft** [comment]
This feature was completed with the release of .NET 8 and .NET Monitor 8.
