### ISSUE TITLE
DumpTest with type Full frequently timeouts on MacOS tests

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-monitor#440]
https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E7+definition%3Adotnet-monitor-ci+name%3ADumpTest

Example test output:
```
[Monitor] User Settings Path: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cbb48c76-b7c1-4a16-8980-0dc76c016be3/UserConfig/settings.json
[Monitor] Path: /Users/runner/work/1/s/artifacts/bin/dotnet-monitor/Release/netcoreapp3.1/dotnet-monitor.dll
[Monitor] Args: collect --urls http://127.0.0.1:0 --metricUrls http://127.0.0.1:0 --no-auth
[Monitor] Begin Environment:
[Monitor] - COMPlus_EnableDiagnostics = 0
[Monitor] - Logging__Console__FormatterName = json
[Monitor] - Logging__LogLevel__Microsoft.Diagnostics.Tools.Monitor.Startup = Debug
[Monitor] - DotnetMonitorTestSettings__SharedConfigDirectoryOverride = /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cbb48c76-b7c1-4a16-8980-0dc76c016be3/SharedConfig
[Monitor] - DotnetMonitorTestSettings__UserConfigDirectoryOverride = /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cbb48c76-b7c1-4a16-8980-0dc76c016be3/UserConfig
[Monitor] End Environment:
[Monitor] Starting...
[Monitor] Process ID: 2593
[Monitor] Default Address: http://127.0.0.1:49967
[Monitor] Metrics Address: http://127.0.0.1:49968
[App1] Path: /Users/runner/work/1/s/artifacts/bin/Microsoft.Diagnostics.Monitoring.UnitTestApp/Release/net6.0/Microsoft.Diagnostics.Monitoring.UnitTestApp.dll
[App1] Args: AsyncWait
[App1] Begin Environment:
[App1] - COMPlus_EnableDiagnostics = 1
[App1] End Environment:
[App1] Starting...
[App1] Process ID: 2594
-> Method: GET, RequestUri: 'http://127.0.0.1:49967/processes/2594', Version: 1.1, Content: <null>, Headers:
{
  Accept: application/json
}
<- StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Tue, 15 Jun 2021 12:26:03 GMT
  Server: Kestrel
  Transfer-Encoding: chunked
  Content-Type: application/json; charset=utf-8
}
-> Method: GET, RequestUri: 'http://127.0.0.1:49967/dump/2594?type=Full', Version: 1.1, Content: <null>, Headers:
{
  Accept: application/octet-stream
}
[App1] Stopping...
[App1] Waiting for exit...
[App1] Exit Code: 137
[App1] Warning: Exception thrown while awaiting task: System.IO.IOException: Operation canceled
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in System.Net.Sockets.dll:token 0x60002e2+0x8
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token) in System.Net.Sockets.dll:token 0x60002dc+0x2d
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken) in System.IO.Pipes.dll:token 0x60000ea+0xd1
   --- End of inner exception stack trace ---
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken) in System.IO.Pipes.dll:token 0x60000ea+0xd1
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken) in System.Private.CoreLib.dll:token 0x600579c+0x2c4
   at System.IO.StreamReader.ReadLineAsyncInternal() in System.Private.CoreLib.dll:token 0x6005794+0x319
   at Microsoft.Diagnostics.Monitoring.TestCommon.LoggingRunnerAdapter.ReadLinesAsync(StreamReader reader, List`1 lines, Action`1 callback, CancellationToken token) in /_/src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/LoggingRunnerAdapter.cs:line 139
   at Microsoft.Diagnostics.Monitoring.TestCommon.TaskExtensions.SafeAwait(Task task, ITestOutputHelper outputHelper) in /_/src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TaskExtensions.cs:line 19
[App1] Warning: Exception thrown while awaiting task: System.IO.IOException: Operation canceled
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in System.Net.Sockets.dll:token 0x60002e2+0x8
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token) in System.Net.Sockets.dll:token 0x60002dc+0x2d
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken) in System.IO.Pipes.dll:token 0x60000ea+0xd1
   --- End of inner exception stack trace ---
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken) in System.IO.Pipes.dll:token 0x60000ea+0xd1
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken) in System.Private.CoreLib.dll:token 0x600579c+0x2c4
   at System.IO.StreamReader.ReadLineAsyncInternal() in System.Private.CoreLib.dll:token 0x6005794+0x319
   at Microsoft.Diagnostics.Monitoring.TestCommon.LoggingRunnerAdapter.ReadLinesAsync(StreamReader reader, List`1 lines, Action`1 callback, CancellationToken token) in /_/src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/LoggingRunnerAdapter.cs:line 139
   at Microsoft.Diagnostics.Monitoring.TestCommon.TaskExtensions.SafeAwait(Task task, ITestOutputHelper outputHelper) in /_/src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TaskExtensions.cs:line 19
[App1] Begin Standard Output:
[App1] {"EventId":1,"LogLevel":"Information","Category":"Microsoft.Diagnostics.Monitoring.UnitTestApp.Program","Message":"State: Ready","State":{"Message":"State: Ready","state":"Ready","{OriginalFormat}":"State: {state}"}}
[App1] {"EventId":1,"LogLevel":"Information","Category":"Microsoft.Diagnostics.Monitoring.UnitTestApp.Program","Message":"State: Waiting","State":{"Message":"State: Waiting","state":"Waiting","{OriginalFormat}":"State: {state}"}}
[App1] {"EventId":2,"LogLevel":"Debug","Category":"Microsoft.Diagnostics.Monitoring.UnitTestApp.Program","Message":"Received command: StartScenario; Expected: True","State":{"Message":"Received command: StartScenario; Expected: True","command":"StartScenario","expected":true,"{OriginalFormat}":"Received command: {command}; Expected: {expected}"}}
[App1] {"EventId":1,"LogLevel":"Information","Category":"Microsoft.Diagnostics.Monitoring.UnitTestApp.Program","Message":"State: Executing","State":{"Message":"State: Executing","state":"Executing","{OriginalFormat}":"State: {state}"}}
[App1] {"EventId":1,"LogLevel":"Information","Category":"Microsoft.Diagnostics.Monitoring.UnitTestApp.Program","Message":"State: Waiting","State":{"Message":"State: Waiting","state":"Waiting","{OriginalFormat}":"State: {state}"}}
[App1] End Standard Output
[App1] Begin Standard Error:
[App1] End Standard Error
[Monitor] Stopping...
[Monitor] Waiting for exit...
[Monitor] Exit Code: 137
[Monitor] Warning: Exception thrown while awaiting task: System.IO.IOException: Operation canceled
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in System.Net.Sockets.dll:token 0x60002e2+0x8
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token) in System.Net.Sockets.dll:token 0x60002dc+0x2d
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken) in System.IO.Pipes.dll:token 0x60000ea+0xd1
   --- End of inner exception stack trace ---
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken) in System.IO.Pipes.dll:token 0x60000ea+0xd1
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken) in System.Private.CoreLib.dll:token 0x600579c+0x2c4
   at System.IO.StreamReader.ReadLineAsyncInternal() in System.Private.CoreLib.dll:token 0x6005794+0x319
   at Microsoft.Diagnostics.Monitoring.TestCommon.LoggingRunnerAdapter.ReadLinesAsync(StreamReader reader, List`1 lines, Action`1 callback, CancellationToken token) in /_/src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/LoggingRunnerAdapter.cs:line 139
   at Microsoft.Diagnostics.Monitoring.TestCommon.TaskExtensions.SafeAwait(Task task, ITestOutputHelper outputHelper) in /_/src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TaskExtensions.cs:line 19
[Monitor] Warning: Exception thrown while awaiting task: System.IO.IOException: Operation canceled
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in System.Net.Sockets.dll:token 0x60002e2+0x8
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token) in System.Net.Sockets.dll:token 0x60002dc+0x2d
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken) in System.IO.Pipes.dll:token 0x60000ea+0xd1
   --- End of inner exception stack trace ---
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken) in System.IO.Pipes.dll:token 0x60000ea+0xd1
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken) in System.Private.CoreLib.dll:token 0x600579c+0x2c4
   at System.IO.StreamReader.ReadLineAsyncInternal() in System.Private.CoreLib.dll:token 0x6005794+0x319
   at Microsoft.Diagnostics.Monitoring.TestCommon.LoggingRunnerAdapter.ReadLinesAsync(StreamReader reader, List`1 lines, Action`1 callback, CancellationToken token) in /_/src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/LoggingRunnerAdapter.cs:line 139
   at Microsoft.Diagnostics.Monitoring.TestCommon.TaskExtensions.SafeAwait(Task task, ITestOutputHelper outputHelper) in /_/src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TaskExtensions.cs:line 19
[Monitor] Begin Standard Output:
[Monitor] {"Timestamp":"12:25:53 ","EventId":13,"LogLevel":"Warning","Category":"Microsoft.Diagnostics.Tools.Monitor.Startup","Message":"WARNING: Authentication has been disabled. This can pose a security risk and is not intended for production environments.","State":{"Message":"WARNING: Authentication has been disabled. This can pose a security risk and is not intended for production environments.","{OriginalFormat}":"WARNING: Authentication has been disabled. This can pose a security risk and is not intended for production environments."},"Scopes":[]}
[Monitor] {"Timestamp":"12:25:53 ","EventId":0,"LogLevel":"Warning","Category":"Microsoft.AspNetCore.Server.Kestrel","Message":"Overriding address(es) \u0027http://127.0.0.1:0\u0027. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.","State":{"Message":"Overriding address(es) \u0027http://127.0.0.1:0\u0027. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.","addresses":"http://127.0.0.1:0","{OriginalFormat}":"Overriding address(es) \u0027{addresses}\u0027. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead."},"Scopes":[]}
[Monitor] {"Timestamp":"12:25:53 ","EventId":14,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Now listening on: http://127.0.0.1:49967","State":{"Message":"Now listening on: http://127.0.0.1:49967","address":"http://127.0.0.1:49967","{OriginalFormat}":"Now listening on: {address}"},"Scopes":[]}
[Monitor] {"Timestamp":"12:25:53 ","EventId":14,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Now listening on: http://127.0.0.1:49968","State":{"Message":"Now listening on: http://127.0.0.1:49968","address":"http://127.0.0.1:49968","{OriginalFormat}":"Now listening on: {address}"},"Scopes":[]}
[Monitor] {"Timestamp":"12:25:53 ","EventId":16,"LogLevel":"Debug","Category":"Microsoft.Diagnostics.Tools.Monitor.Startup","Message":"Bound default address: http://127.0.0.1:49967","State":{"Message":"Bound default address: http://127.0.0.1:49967","address":"http://127.0.0.1:49967","{OriginalFormat}":"Bound default address: {address}"},"Scopes":[]}
[Monitor] {"Timestamp":"12:25:53 ","EventId":17,"LogLevel":"Debug","Category":"Microsoft.Diagnostics.Tools.Monitor.Startup","Message":"Bound metrics address: http://127.0.0.1:49968","State":{"Message":"Bound metrics address: http://127.0.0.1:49968","address":"http://127.0.0.1:49968","{OriginalFormat}":"Bound metrics address: {address}"},"Scopes":[]}
[Monitor] {"Timestamp":"12:25:53 ","EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Application started. Press Ctrl\u002BC to shut down.","State":{"Message":"Application started. Press Ctrl\u002BC to shut down.","{OriginalFormat}":"Application started. Press Ctrl\u002BC to shut down."},"Scopes":[]}
[Monitor] {"Timestamp":"12:25:53 ","EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Hosting environment: Production","State":{"Message":"Hosting environment: Production","envName":"Production","{OriginalFormat}":"Hosting environment: {envName}"},"Scopes":[]}
[Monitor] {"Timestamp":"12:25:53 ","EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Content root path: /Users/runner/work/1/s/artifacts/bin/dotnet-monitor/Release/netcoreapp3.1/","State":{"Message":"Content root path: /Users/runner/work/1/s/artifacts/bin/dotnet-monitor/Release/netcoreapp3.1/","contentRoot":"/Users/runner/work/1/s/artifacts/bin/dotnet-monitor/Release/netcoreapp3.1/","{OriginalFormat}":"Content root path: {contentRoot}"},"Scopes":[]}
[Monitor] {"Timestamp":"12:26:03 ","EventId":5,"LogLevel":"Information","Category":"Microsoft.Diagnostics.Monitoring.RestServer.Controllers.DiagController","Message":"Written to HTTP stream.","State":{"Message":"Written to HTTP stream.","{OriginalFormat}":"Written to HTTP stream."},"Scopes":[{"Message":"SpanId:91eeb20c483a0ca7, TraceId:5609c96c020483e59c7ec9b652f69784, ParentId:0000000000000000","SpanId":"91eeb20c483a0ca7","TraceId":"5609c96c020483e59c7ec9b652f69784","ParentId":"0000000000000000"},{"Message":"ConnectionId:0HM9FV2UQNG8N","ConnectionId":"0HM9FV2UQNG8N"},{"Message":"RequestPath:/processes/2594 RequestId:0HM9FV2UQNG8N:00000002","RequestId":"0HM9FV2UQNG8N:00000002","RequestPath":"/processes/2594"},{"Message":"Microsoft.Diagnostics.Monitoring.RestServer.Controllers.DiagController.GetProcessInfo (Microsoft.Diagnostics.Monitoring.RestServer)","ActionId":"125616e6-d334-4933-bf99-dc810cd35538","ActionName":"Microsoft.Diagnostics.Monitoring.RestServer.Controllers.DiagController.GetProcessInfo (Microsoft.Diagnostics.Monitoring.RestServer)"},{"Message":"ArtifactSource_ProcessId:2594 ArtifactSource_RuntimeInstanceCookie:1300215ccf4d424e8d4936122a065d0b","ArtifactSource_ProcessId":"2594","ArtifactSource_RuntimeInstanceCookie":"1300215ccf4d424e8d4936122a065d0b"}]}
[Monitor] End Standard Output
[Monitor] Begin Standard Error:
[Monitor] End Standard Error
```

**Comment by jander-msft** [comment]
This may have been mitigated with increasing the dump collection timeout. However, keep this open for a little while longer and monitor the builds for this issue.
